// <auto-generated />
namespace reviewIt.Domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class ss : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ss));
        
        string IMigrationMetadata.Id
        {
            get { return "201609300844135_ss"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
